### PR TITLE
Remove `cross` option for generator parameters

### PR DESCRIPTION
**Pull request by ggonzr**
Related topic: https://cms-talk.web.cern.ch/t/problem-with-adding-cross-section-to-mcm-requests/36272/3

### CODE REVIEW

**Review by lmoureaux — APPROVED** [review]

**Comment by lmoureaux** [comment]
Seems to be working in `-dev` (but I don't have a broken setup to compare to)

**Comment by ggonzr** [comment]
I suggest asking the colleague who reported this for the details of the request tried to create so that we can replicate it first in dev before merging this. Please could you ask for the details and replicate this in dev first? Thanks

**Comment by lmoureaux** [comment]
I reproduced in production McM with [HIG-RunIISummer20UL18wmLHEGEN-13372](https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=HIG-RunIISummer20UL18wmLHEGEN-13372&page=0&shown=127). This request isn't in the dev database but I couldn't reproduce the same message when validating similar requests.

**Comment by ggonzr** [comment]
I synced the data for both environments and now the request is available in dev [HIG-RunIISummer20UL18wmLHEGEN-13372](https://cms-pdmv-dev.web.cern.ch/mcm/requests?prepid=HIG-RunIISummer20UL18wmLHEGEN-13372&page=0&shown=127). Please can you reproduce the issue and check if it is solved.

**Comment by lmoureaux** [comment]
Hi Geovanny, I confirmed that the API was used to change the `cross_section` in the generator parameters so it passed the check. I still think this fix is needed

**Pull request merged**
