### PR TITLE
Essential of acnkowledging invalidations

### PR DESCRIPTION
**Pull request by vlimant**
this is a way to forget about the painful hand-shake on invalidations.
ops can then pull in and acknowledge the things to take to the bin.

### CODE REVIEW

**Comment by srimanob** [comment]
@franzoni @anorkus 
Hi, should we discuss about this during the next preMccM? Since we have several requests to resubmit, this should help us to reduce the hand-shake of invalidation announcements.

Thanks,
Phat

**Comment by vlimant** [comment]
it might be worth adding an extra status for invalidations new -> announced -> acknowledge and let ops toggle from either new or announced to acknowledge.
Which means ops will take care of passing everything in the db to acknowledge to put everything consistent.

**Comment by vlimant** [comment]
How far are we with this ?

**Comment by anorkus** [comment]
Should be pulled to -int and -prod with newest tag tomorrow.

**Comment by vlimant** [comment]
how is it functioning, have you massaged things ? can we test things before deployment ?

**Comment by anorkus** [comment]
i can pull thing to -dev to test more. But the this API only changes the status of invalidation, so it shouldn't need so much testing.

**Comment by vlimant** [comment]
right, OK. one should test the allow_user functionality, that's new, and maybe you want to set this as an entry in settings

**Comment by anorkus** [comment]
already moved to entry in settings

**Comment by anorkus** [comment]
the changes now are in -dev. You can try to see if you are able to access it. Also, general question do we really want that this method can be access on user level?

**Comment by vlimant** [comment]
the access is user level, but only Matteo and myself, or whoever is in setting (admin protected) would get actual access to it.
https://cms-pdmv-dev.cern.ch/mcm/invalidations?status=acknowledged&page=0&shown=13
functions. please try yourself to acknowledge something to is it failing for someone else.

**Comment by anorkus** [comment]
well, i could acknowledge it as generator_contact

**Comment by vlimant** [comment]
the change in  mcm/rest_api/RestAPIMethod.py should prevent anyone else them vlimant and cremone to access the resource.

**Comment by anorkus** [comment]
actually it does not

**Comment by vlimant** [comment]
yes :-( the logic is wrong.
I put the check under 
if not self.authenticator.can_access(user_p.get_username()):
while it should be before most likely

**Comment by anorkus** [comment]
well... changed that acknowledgement can be by for admin. If user has no permission, but is in list of access_users -> he will still be able to access.

**Comment by vlimant** [comment]
sounds perfect to me

**Comment by vlimant** [comment]
any further issue with this preventing deployment ?

**Comment by franzoni** [comment]
Ciao Jean-Roch,
we want to understand the operational implications of this change: for ops, for the req managers. Phat is drafting an email to you/ops to kick-start the process. He's in a conference today/this week, the message should come soon.
Cheers, G.

**Comment by vlimant** [comment]
In a nutshell, as a start, we (pdmv/ops) will set everything acknowkledge, as it's the case without operating any actual rejection/invalidation.
Then, ops modules will poll invalidations in announced status (not new, new if for you) and will operate rejection and invalidation automatically, and push ack the acknowledge api.
i.e. whatever is done on mcm side right now is unchanged, it's just that ops does not have to get to a keyboard and do something, it will be done automatically.

Of course if someone makes an invalidation, and announces it, then wants to take it back ; then yes, it can be hard to go back. One just have to be careful in what gets announced (anyways ?)

**Comment by vlimant** [comment]
This https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/7013.html is painful. As I was suspected.

**Comment by srimanob** [comment]
Sorry for late reply. I've a chat with JR about the steps. In practical, we have the same step as before. 
(1) We reset requests
(2) We announce the invalidation
(3) Ops will pick up the announcement and operate it automatically and set acknowledge (maybe JR can help to explain about "set acknowledge")
(4) If we reset some samples unexpectedly, we will clean them first from the invalidation announcement. I think this function is already implemented in McM. Antanas could you please confirm. 

In general, I think from the McM point of view, we are almost at the same place. I suggest we merge this PR to the McM prod.

Thanks.

**Comment by vlimant** [comment]
@anorkus please remember to raise the access to admin, which should let admins, matteo and myself only through

**Comment by vlimant** [comment]
and class Clearer() should be changed to put whatever status to the invalidation you prefer, but not announced

**Comment by srimanob** [comment]
I think we should also mention to request manager to announce the invalidation anytime they reset. So it will not collide with later invalidation. Just to make the McM cleans.

**Comment by vlimant** [comment]
can one please go and remove the "?" and "None Yet" documents ?
@srminanob : you might need a "select several" => announce button to selectively announce invalidations

**Comment by anorkus** [comment]
deleted those two documents from DB.

**Pull request merged**
