### PR TITLE
Allow `generator contacts` to update the `dataset_name` attribute

### PR DESCRIPTION
**Pull request by ggonzr**
Solves: #1116

1. Allow the described role to modify the dataset name after the validation step.

### CODE REVIEW

**Comment by sunilUIET** [comment]
Thanks @ggonzr , can we add permission to edit "extension" and "process_string" as well? It helps to resolve dataset name conflicts.

**Comment by ggonzr** [comment]
Also, should we allow `generator_conveners` to modify them?

**Comment by sunilUIET** [comment]
Yes, we can do that

**Comment by ggonzr** [comment]
I have deployed this change into the development environment and prepared a test request [1]. @tvami please can you check it, modify its `dataset_name` and let us know if the update solves your requirement. If it is okay, @sunilUIET please can you approve the change to merge it. Thanks.

References:
[1]. Test request: https://cms-pdmv-dev.web.cern.ch/mcm/requests?prepid=PPD-Run3Summer21wmLHEGS-00003&page=0&shown=127

**Comment by tvami** [comment]
hi @ggonzr looks good, thanks a lot! @sunilUIET please go ahead with the approval if you agree, thanks!

**Review by sunilUIET — APPROVED** [review]

**Pull request merged**
