### PR TITLE
Suggestion for output-datatier-branching in flow

### PR DESCRIPTION
**Pull request by vlimant**
To be reviewed for possible typos. 
TaskChain should be checked to not be broken.
Flows that have "use_datatier" mentioned in "request_parameters" will try to pick the corresponding output.

Came out easier than I thought.

### CODE REVIEW

**Comment by vlimant** [comment]
There is a typo at len()!=0 to raise exception, while it should be ==
It is also not sufficient if a taskchain had two output with the same datatier in output.

**Comment by vlimant** [comment]
@srimanob this PR has not merged, therefore you cannot be using the feature it contains

**Comment by srimanob** [comment]
@anorkus 
Could you please merge it to dev? Thanks very much.

**Comment by vlimant** [comment]
Hi, what was so wrong with this suggestion that https://cms-pdmv.cern.ch/mcm/settings?prepid=datatier_input was introduced instead ?

**Pull request closed without merging**
